name: shouldly
description: A simple, extensible BDD assertion library which focuses on giving great error messages when the assertion fails.
version: 0.1.1
homepage: https://github.com/AndrewPiterov/shouldly

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
dev_dependencies:
  lint: ^1.7.2
  test: ^1.17.12 
