name: shouldly
description: A simple, extensible BDD assertion library which focuses on giving great error messages when the assertion fails.
version: 0.4.1+1
homepage: https://github.com/AndrewPiterov/shouldly

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  given_when_then_unit_test: ^0.0.10
  lint: ^1.8.2
  test: ^1.20.1
