name: shouldly
description: A simple, extensible, readable BDD assertion library.
version: 0.1.0
homepage: https://github.com/AndrewPiterov/shouldly

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
dev_dependencies:
  lint: ^1.7.2
  test: ^1.17.12 